services:
  - type: web
    name: eic-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=2048
    healthCheckPath: /
    autoDeploy: true 